name: 'Use Private Action'
description: 'Clones private action into a runner and triggers it'

inputs:
  uses:
    description: "owner/repository containing the action"
    required: true
  github_app_id:
    description: "GitHub App Id"
    required: true
  github_app_private_key:
    description: "GitHub App Private Key"
    required: true
  with:
    description: "List of key/value inputs"
    required: false

runs:
  
  using: "composite"
  
  steps:

    - name: Cleanup & get private action owner
      id: private-action-owner
      run: |
        # Cleanup existing actions in this directory
        rm -rf ./actions/private-action
        # Returns the owner/repo
        echo "::set-output name=action_repo::$(echo ${{ inputs.uses }} | awk -F '@' '{print $1}')"
        # Returns the owner (i.e. org name only)
        echo "::set-output name=organization::$(echo ${{ inputs.uses }} | awk -F '/' '{print $1}')"
        # Returns the repo name only
        echo "::set-output name=branch::$(echo ${{ inputs.uses }} | awk -F '/' '{print $2}' | awk -F '@' '{print $2}')"
        # Return list of inputs
        INPUTS=$(cat <<EOF
        ${{ inputs.with }}
        EOF
        )
        echo $INPUTS
      shell: bash

    - name: Get Token 
      id: github-app
      uses: peter-murray/workflow-application-token-action@v1
      with:
        application_id: ${{ inputs.github_app_id }}
        application_private_key: ${{ inputs.github_app_private_key }}
        organization: ${{ steps.private-action-owner.outputs.organization }}

    - name: Check-out the simple private action
      uses: actions/checkout@v2
      with:
        repository: ${{ steps.private-action-owner.outputs.action_repo }}
        ref: ${{ steps.private-action-owner.outputs.branch }}
        path: actions/private-action
        token: ${{ steps.github-app.outputs.token }}
        persist-credentials: false

    - name: Run private action
      uses: ./actions/private-action
